include :
  - project: 'devops/ci'
    ref: master
    file: app-template.gitlab-ci.yml

variables:
  DEV_BACKEND_URL: "https://licenses.dbk.dev.burlingtonenglish.in/"
  DEV_BOOK_KEY: $DEV_BOOK_CI_KEY
  PROD_BACKEND_URL: "https://licenses.dbk.burlingtonenglish.in/"
  PROD_BOOK_KEY: $PROD_BOOK_CI_KEY

stages:
  - package-dev
  - release-dev
  - package-prod
  - release-prod

package-linux-dev:
  stage: package-dev
  extends: .package
  variables: 
    DOCKER_FILE: 'Dockerfile.linux'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

package-android-dev:
  stage: package-dev
  extends: .package
  variables: 
    DOCKER_FILE: 'Dockerfile.android'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

package-windows-dev:
  stage: package-dev
  extends: .package.windows
  variables: 
    DOCKER_FILE: 'Dockerfile.windows'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

release-linux-dev:
  needs:
    - package-linux-dev
  stage: release-dev
  extends: .release

release-android-dev:
  needs:
    - package-android-dev
  stage: release-dev
  extends: .release

release-windows-dev:
  needs:
    - package-windows-dev
  stage: release-dev
  extends: .release  


package-linux-prod:
  stage: package-prod
  extends: .package
  variables: 
    DOCKER_FILE: 'Dockerfile.linux'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

package-android-prod:
  stage: package-prod
  extends: .package
  variables: 
    DOCKER_FILE: 'Dockerfile.android'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

package-windows-prod:
  stage: package-prod
  extends: .package.windows
  variables: 
    DOCKER_FILE: 'Dockerfile.windows'
    DOCKER_BUILD_OPTIONS: '--build-arg '
  when: manual  

release-linux-prod:
  needs:
    - package-linux-prod
  stage: release-prod
  extends: .release

release-android-prod:
  needs:
    - package-android-prod
  stage: release-prod
  extends: .release

release-windows-prod:
  needs:
    - package-windows-prod
  stage: release-prod
  extends: .release    