include :
  - project: 'devops/ci'
    ref: master
    file: app-template.gitlab-ci.yml

variables:
  DEV_BACKEND_URL: "https://licenses.dbk.dev.burlingtonenglish.in/"
  DEV_BOOK_KEY: $DEV_BOOK_CI_KEY
  PROD_BACKEND_URL: "https://licenses.dbk.burlingtonenglish.in/"
  PROD_BOOK_KEY: $PROD_BOOK_CI_KEY

stages:
  - package
  - release

package-linux-dev:
  stage: package
  extends: .package
  variables:
    DOCKER_FILE: 'Dockerfile.linux'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$DEV_BACKEND_URL --build-arg BOOK_KEY=$DEV_BOOK_KEY --build-arg BUILD_ENV=Dev'
  when: manual

package-android-dev:
  stage: package
  extends: .package
  variables:
    DOCKER_FILE: 'Dockerfile.android'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$DEV_BACKEND_URL --build-arg BOOK_KEY=$DEV_BOOK_KEY --build-arg BUILD_ENV=Dev'
  when: manual

package-windows-dev:
  stage: package
  extends: .package.windows
  variables:
    DOCKER_FILE: 'Dockerfile.windows'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$DEV_BACKEND_URL --build-arg BOOK_KEY=$DEV_BOOK_KEY --build-arg BUILD_ENV=Dev'
  when: manual

release-linux-dev:
  needs:
    - package-linux-dev
  stage: package
  extends: .release

release-android-dev:
  needs:
    - package-android-dev
  stage: package
  extends: .release

release-windows-dev:
  needs:
    - package-windows-dev
  stage: package
  extends: .release


package-linux-prod:
  stage: package
  extends: .package
  variables:
    DOCKER_FILE: 'Dockerfile.linux'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$PROD_BACKEND_URL --build-arg BOOK_KEY=$PROD_BOOK_KEY --build-arg BUILD_ENV=Prod'
  when: manual

package-android-prod:
  stage: package
  extends: .package
  variables:
    DOCKER_FILE: 'Dockerfile.android'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$PROD_BACKEND_URL --build-arg BOOK_KEY=$PROD_BOOK_KEY --build-arg BUILD_ENV=Prod'
  when: manual

package-windows-prod:
  stage: package
  extends: .package.windows
  variables:
    DOCKER_FILE: 'Dockerfile.windows'
    DOCKER_BUILD_OPTIONS: '--build-arg BACKEND_URL=$PROD_BACKEND_URL --build-arg BOOK_KEY=$PROD_BOOK_KEY --build-arg BUILD_ENV=Prod'
  when: manual

release-linux-prod:
  needs:
    - package-linux-prod
  stage: package
  extends: .release

release-android-prod:
  needs:
    - package-android-prod
  stage: package
  extends: .release

release-windows-prod:
  needs:
    - package-windows-prod
  stage: package
  extends: .release
